### ISSUE TITLE
Digawe github pages sisan

### ISSUE THREAD

**Issue by stormbeforesunsetbee** [Musshal/js-calculator#1]
Sal, kie kan aplikasi client side oh ya? Suka digawe github pages sisan oh

**Comment by faishaldev** [comment]
> Sal, kie kan aplikasi client side oh ya? Suka digawe github pages sisan oh

Iya, ngko tak coba

Edit:
Done.
https://musshal.github.io/js-calculator/

**Comment by stormbeforesunsetbee** [comment]
About repone anapa sal
![Screenshot from 2021-05-11 13-17-46](https://user-images.githubusercontent.com/6300910/117767639-69b26880-b25b-11eb-873d-49037562870d.png)

Btw link e sing bener https://musshal.github.io/js-calculator/
